### PR TITLE
Image corruption can occur when multiple treatments for the same image are requested concurrently

### PR DESCRIPTION
**Pull request by hasheniuk**
BroadleafCommerce/QA#3094
use ConcurrentFileOutputStream component to write file

### CODE REVIEW

**Comment by hasheniuk** [comment]
Requires BroadleafCommerce/BroadleafCommerce#1745

**Review by jefffischer — APPROVED** [review]
Seems reasonable. However, it looks like the build is failing.

**Comment by jefffischer** [comment]
Also, I think the customer mentioned they were using version 1.1 of the amazon module.

**Comment by hasheniuk** [comment]
@jefffischer 
I suppose it fails because of tests. In `AbstractS3Test. resetAllProperties()` there are  `aws.s3.accessKeyId` and `aws.s3.secretKey` not correct, so all tests fails because of it. Is it possible to skip tests on Jenkins check?

**Comment by jefffischer** [comment]
@hasheniuk We need to resolve failures (either compilation or test) before merging PRs.

Taking a look...

**Comment by jefffischer** [comment]
This is what Jenkins is showing. I don't think it's missing credentials for AWS, but rather some other problem. We need to try to address these tests before continuing:
```
Tests in error: 
  checkForMissingSecretKey(org.broadleafcommerce.vendor.amazon.s3.S3ConfigurationServiceTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  checkForBadBucketRegion(org.broadleafcommerce.vendor.amazon.s3.S3ConfigurationServiceTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  checkForAllPropertiesSet(org.broadleafcommerce.vendor.amazon.s3.S3ConfigurationServiceTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  checkForMissingCredential(org.broadleafcommerce.vendor.amazon.s3.S3ConfigurationServiceTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  checkForMissingAccessKeyId(org.broadleafcommerce.vendor.amazon.s3.S3ConfigurationServiceTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  testSubDirectory(org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProviderTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  testSubDirectoryWithSlashes(org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProviderTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  testSubDirectoryTree(org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProviderTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  testFileProcesses(org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProviderTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  testNotFoundReturnsNonExistentFile(org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProviderTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  testSiteSpecificFile(org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProviderTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
  testRemoveAddedResourceByName(org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProviderTest): com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
```

**Comment by hasheniuk** [comment]
@jefffischer 
Open PR for 1.1 version BroadleafCommerce/blc-amazon#16

**Pull request closed without merging**
